apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-service-server-deployment
  labels:
    app: edge-service-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-service-server
  template:
    metadata:
      labels:
        app: edge-service-server
    spec:
      containers:
      - name: edge-service-server
        image: pieterpa/edge-service
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8050
        resources:
          limits:
            cpu: 0.2
            memory: "200Mi"
        env:
        - name: BRAND_SERVICE_BASEURL
          value: "brand-service-server:8052"
        - name: MODEL_SERVICE_BASEURL
          value: "model-service-server:8053"
---
apiVersion: v1
kind: Service
metadata:                     
  name: edge-service-server
  labels:
    app: edge-service-server
spec:                         
  type: NodePort
  selector:
    app: edge-service-server
  ports:
  - name: http
    port: 8050
    targetPort: 8050
