apiVersion: v1
kind: Service
metadata:
  name: brand-service-mongo
  labels:
    app: brand-service
spec:
  ports:
    - port: 27017
  selector:
    app: brand-service
    tier: mongo
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: brand-service-mongo-deployment
  labels:
    app: brand-service
spec:
  selector:
    matchLabels:
      app: brand-service
      tier: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: brand-service
        tier: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - containerPort: 27017 
          name: mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: brand-service-server-deployment
  labels:
    app: brand-service-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brand-service-server
  template:
    metadata:
      labels:
        app: brand-service-server
    spec:
      containers:
      - name: brand-service-server
        image: pieterpa/brand-service
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8052
        resources:
          limits:
            cpu: 0.2
            memory: "200Mi"
        env:
        - name: MONGODB_HOST
          value: "brand-service-mongo"
        - name: MONGODB_PORT
          value: "27017"
---
apiVersion: v1
kind: Service
metadata:                     
  name: brand-service-server
  labels:
    app: brand-service-server
spec:                         
  type: NodePort
  selector:
    app: brand-service-server
  ports:
  - name: http
    port: 8052
    targetPort: 8052
---
apiVersion: v1
kind: Service
metadata:                     
  name: model-service-postgres
  labels:
    app: model-service
spec:                         
  ports:
    - port: 5432
  selector:
    app: model-service
    tier: postgres
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service-postgres-deployment
  labels:
    app: model-service
spec:
  selector:
    matchLabels:
      app: model-service
      tier: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: model-service
        tier: postgres
    spec:
      containers:
        - image: postgres:latest
          name: postgres
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              value: modeldata
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: apt-team7-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apt-team7-secret
                  key: POSTGRES_PASSWORD
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service-server-deployment
  labels:
    app: model-service-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-service-server
  template:
    metadata:
      labels:
        app: model-service-server
    spec:
      containers:
      - name: model-service-server
        image: pieterpa/model-service
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8053
        resources:
          limits:
            cpu: 0.2
            memory: "200Mi"
        env:
        - name: POSTGRES_HOST
          value: "model-service-postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "modeldata"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: apt-team7-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: apt-team7-secret
              key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:                     
  name: model-service-server
  labels:
    app: model-service-server
spec:                         
  type: NodePort
  selector:
    app: model-service-server
  ports:
  - name: http
    port: 8053
    targetPort: 8053
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-service-server-deployment
  labels:
    app: edge-service-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-service-server
  template:
    metadata:
      labels:
        app: edge-service-server
    spec:
      containers:
      - name: edge-service-server
        image: pieterpa/edge-service
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8050
        resources:
          limits:
            cpu: 0.2
            memory: "200Mi"
        env:
        - name: BRAND_SERVICE_BASEURL
          value: "brand-service-server:8052"
        - name: MODEL_SERVICE_BASEURL
          value: "model-service-server:8053"
---
apiVersion: v1
kind: Service
metadata:                     
  name: edge-service-server
  labels:
    app: edge-service-server
spec:                         
  type: NodePort
  selector:
    app: edge-service-server
  ports:
  - name: http
    port: 8050
    targetPort: 8050
